name = "HiBitSet"
uuid = "290bb71e-4df0-4a82-a724-4bbee9184de7"
version = "0.1.0"
authors = ["Talom Lael <gesee37@gmail.com>"]

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"

[targets]
test = ["Coverage"]